# Generated by Django 4.0.4 on 2022-04-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_posttranslation_old_md_alter_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='widget',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
